# Generated by Django 5.1.7 on 2025-04-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(default=0)),
                ('sugars', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishdiva.nutrition')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('N', 'Generic'), ('H', 'Healthy'), ('VG', 'Vegetarian'), ('V', 'Vegan'), ('GF', 'GlutenFree')], max_length=2)),
                ('instructions', models.CharField(max_length=200000)),
                ('ingredients', models.ManyToManyField(to='dishdiva.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('ingredients', models.ManyToManyField(to='dishdiva.ingredient')),
                ('recipes', models.ManyToManyField(to='dishdiva.recipe')),
            ],
        ),
    ]
